#!/usr/bin/env python
import os

print("Generating the templates..")
os.system("go run generator.go")
print("Clearing existing files")
os.system("cd types && rm ./*_hasgo*")
print("updating modules..")
os.system("go mod tidy")
print("Installing new Hasgo lib")
os.system("go install")
print("Generating source files...")
os.system("cd types && go generate ./...")
print("Formatting files..")
os.system("gofmt -s -w .")
print("Running unit tests")
os.system("cd types/ && go test ./... && cd -")
