#!/usr/bin/env python
import os

print("Generating the templates..")
os.system("go run generator.go")
print("Clearing existing files")
os.system("rm types/*_hasgo*")
print("Installing new Hasgo lib")
os.system("go install")
print("Generating source files...")
os.system("go generate ./...")
print("Formatting files..")
os.system("gofmt -w .")
print("Running unit tests")
os.system("cd types/ && go test ./... && cd -")
