// Code generated by go generate; DO NOT EDIT.
package main

var hasgoTemplates = map[string]string{
	"Filter.go": `
func (s SliceType) Filter(f func(ElementType) bool) (out SliceType) {
	for _, v := range s {
		if f(v) {
			out = append(out, v)
		}
	}
	return
}
`,
	"Init.go": `
// Take n-1 elements from a slice, where n = len(list)
func (s SliceType) Init() (out SliceType) {
	slicecopy := append([]ElementType(nil), s...)
	return slicecopy[:len(s)-1]
}
`,
	"Sum.go": `
func (s SliceType) Sum() ElementType {
	var sum ElementType
	for _, v := range s {
		sum += v
	}
	return sum
}
`,
}

const (
	ForNumbers = "ForNumbers"
	ForStrings = "ForStrings"
)

var funcDomains = map[string][]string{
	"Filter.go": []string{ForNumbers, ForStrings},
	"Init.go":   []string{ForNumbers, ForStrings},
	"Sum.go":    []string{ForNumbers, ForStrings},
}
