// Code generated by hasgo.go [DO NOT EDIT]
package types

//===============Sum.go=============

func (s Ints) Sum() int64 {
	var sum int64
	for _, v := range s {
		sum += v
	}
	return sum
}

//===============
