// Code generated by hasgo.go [DO NOT EDIT]
package types

//===============Sum.go=============

func (s Ints) Sum() Int {
	var sum Int
	for _, v := range s {
		sum += v
	}
	return sum
}

//===============
