// Code generated by hasgo.go [DO NOT EDIT]
package types

//===============Filter.go=============

func (s Strings) Filter(f func(string) bool) (out Strings) {
	for _, v := range s {
		if f(v) {
			out = append(out, v)
		}
	}
	return
}

//===============
//===============Sum.go=============

func (s Strings) Sum() string {
	var sum string
	for _, v := range s {
		sum += v
	}
	return sum
}

//===============
