// Code generated by hasgo.go [DO NOT EDIT]
package types

//===============Sum.go=============

func (s Strings) Sum() string {
	var sum string
	for _, v := range s {
		sum += v
	}
	return sum
}

//===============
