// Code generated by hasgo.go [DO NOT EDIT]
package types

//===============Filter.go=============

func (s Strings) Filter(f func(string) bool) (out Strings) {
	for _, v := range s {
		if f(v) {
			out = append(out, v)
		}
	}
	return
}

//===============Init.go=============

// Take n-1 elements from a slice, where n = len(list)
func (s Strings) Init() (out Strings) {
	slicecopy := append([]string(nil), s...)
	return slicecopy[:len(s)-1]
}

//===============Sum.go=============

func (s Strings) Sum() string {
	var sum string
	for _, v := range s {
		sum += v
	}
	return sum
}
